services:
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - "./data-storage/data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=learn-postgres-concepts"